[project]
name = "certicertify-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mlritcsedepartment2005-oss", email = "mlritcsedepartment2005@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.94",
    "dotenv>=0.9.9",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "motor>=3.7.1",
    "openpyxl>=3.1.5",
    "pillow>=12.3.0",
    "pydantic>=2.13.5",
    "pymupdf>=1.28.2",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "uvicorn>=0.53.0",
]

[project.scripts]
certicertify-backend = "certicertify_backend:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
